[features]
hooks = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.codegraph]
command = "npx"
args = ["@colbymchenry/codegraph","serve","--mcp"]

[mcp_servers.node_repl]
command = "node_repl"
args = []

[[hooks.UserPromptSubmit]]
hooks = [{ type = "command", command = "node \"F:/pro/codexhono/honoapp/node_modules/tsx/dist/cli.mjs\" \"F:/pro/codexhono/honoapp/src/sse/hookReceive.ts\" hook \"F:/pro/create-todo-cli/.codex\" \"F:/pro/codexhono/honoapp\" \"192.168.110.126\" 3000 user", timeout = 10 }]

[[hooks.Stop]]
hooks = [{ type = "command", command = "node \"F:/pro/codexhono/honoapp/node_modules/tsx/dist/cli.mjs\" \"F:/pro/codexhono/honoapp/src/sse/hookReceive.ts\" hook \"F:/pro/create-todo-cli/.codex\" \"F:/pro/codexhono/honoapp\" \"192.168.110.126\" 3000 assistant", timeout = 10 }]
